-   id: ansible-lint
    name: Ansible-lint
    description: This hook runs ansible-lint.
    entry: ansible-lint
    language: python
    files: \.(yaml|yml)$

-   id: autopep8
    name: autopep8
    entry: autopep8
    language: python
    files: \.py$
    args: [-i]

-   id: forbid-tabs
    name: No-tabs checker
    description: "Forbid files containing tabs to be committed"
    entry: forbid_tabs
    language: python
    files: ''
    exclude: (Makefile|debian/rules)(\.in)?$

-   id: remove-tabs
    name: Tabs remover
    description: "Replace tabs by whitespaces before committing"
    entry: remove_tabs
    language: python
    args: [ --whitespaces-count, '4' ]
    files: ''
    exclude: (Makefile|debian/rules)(\.in)?$

-   id: terraform_fmt
    name: terraform_fmt
    description: Formats terraform scripts into the correct checkstyle
    entry: bin/tf_fmt.sh
    language: script
    files: \.tf$
    exclude: \.terraform\/.*$

-   id: terraform_validate
    name: terraform_validate
    description: Validates terraform scripts syntax
    entry: bin/tf_validate.sh
    language: script
    files: \.tf$
    exclude: \.terraform\/.*$

-   id: yamllint
    name: yamllint
    description: This hook runs yamllint.
    entry: yamllint
    language: python
    types: [file, yaml]
    ignore: (.pre-commit-config.yaml|.pre-commit-hooks.yaml)?$

-   id: prettier
    name: prettier
    entry: prettier
    language: node
    files: \.(js)$
    args: ['--write']
    # Use additional_dependencies to install the actual node package
    minimum_pre_commit_version: 0.12.0

-   id: validate_manifest
    name: Validate Pre-Commit Manifest
    description: This validator validates a pre-commit hooks manifest file
    entry: pre-commit-validate-manifest
    language: python
    files: ^(\.pre-commit-hooks\.yaml|hooks\.yaml)$
