-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: detect-private-key
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
    -   id: autopep8-wrapper
    -   id: debug-statements
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    sha: v1.3.2
    hooks:
    -   id: autopep8
-   repo: https://github.com/willthames/ansible-lint.git
    sha: v3.4.13
    hooks:
    -   id: ansible-lint
        files: \.(yaml|yml)$
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    sha: v1.0.1
    hooks:
    -   id: forbid-tabs
    -   id: remove-tabs
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    sha: v1.0.3
    hooks:
    -   id: python-bandit-vulnerability-check
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    sha: v1.2.0
    hooks:
    -   id: terraform_fmt
-   repo: https://github.com/pre-commit/pre-commit
    sha: v0.16.0
    hooks:
    -   id: validate_config
    -   id: validate_manifest
